image: atlassian/default-image:3

pipelines:
  branches:
    main:
      - step:
          name: Deploy ke Server Produksi
          script:
            - ssh -o StrictHostKeyChecking=no -p 22131 aptika@103.148.29.68 <<EOF
                sudo -u www-data git -C /var/www/html/pengukuran_spbe_opd pull
                mysql -u "$DB_USER" -p"$DB_PASSWD" -e "DROP DATABASE IF EXISTS pengukuran_spbe_opd; CREATE DATABASE pengukuran_spbe_opd CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;"
                mysql -u "$DB_USER" -p"$DB_PASSWD" pengukuran_spbe_opd < /var/www/html/pengukuran_spbe_opd/lke_pengukuran_irb.sql
              EOF
